### ISSUE TITLE
Archivos con BOM

### ISSUE THREAD

**Issue by edittler** [lugfi/organizador-fiuba#14]
Al trabajar con mi editor [Brackets](http://brackets.io/), me di cuenta que sobrescribía todo el archivo `index.html`.

Supuse que estaba en otra codificación y al abrirlo se cambiaba UTF-8, pero el archivo ya se encuentra en esa codificación.

Investigando un poco más, noté un caracter extraño al inicio del archivo que es el caracter BOM, que indica que la codificación UTF-8 se encuentra en ¡¡Big Endian!!

Al correr el siguiente comando, se pueden ver todos los archivos de ese directorio que tienen la marca BOM (y por ende, codificados en Big Endian).

``` sh
find -type f|while read file;do [ "`head -c3 -- "$file"`" == $'\xef\xbb\xbf' ] && echo "found BOM in: $file";done
```

Probé usar otro editor menos intrusivo pero, luego de usarlo un rato, me doy cuenta que el SO (Ubuntu) pasa a reconocer al archivo como un SVG (!)

No se cual es la razón por la cual mantienen UTF-8 con BOM, pero [según el estándar Unicode el uso de BOM ya no es recomendado](http://stackoverflow.com/a/2223926). También [puede haber problemas de visualización en algunos navegadores](https://www.w3.org/International/questions/qa-utf8-bom.es.php) (a mi no me ha pasado por lo menos).

En fin, si no hay una razón para mantener BOM, habría que recodificar los archivos (puedo hacerlo).

**Comment by colltoaction** [comment]
+1

**Comment by edittler** [comment]
En el último commit eliminé esos caracteres, probé el sitio tanto en local como lo que está subido en github y anda bien.
