### ISSUE TITLE
Forzar curso

### ISSUE THREAD

**Issue by fdnk** [lugfi/organizador-fiuba#17]
Estaría bueno que uno pueda marcar que quiere sí o sí cursar con determinados cursos solamente.
Por ejemplo: que sólo me arme horarios con los cursos de Numérico de Tarela o Sassano, exceptuando las demás.

**Comment by francoSpada** [comment]
Tus deseos son órdenes jajajaj

**Comment by edittler** [comment]
No se por qué se cerró el issue, pero la idea está buena. En vez de checkboxs de selección única hay que poner checkbox de seleccion multiples en los cursos. Y obviamente ajustar el java script.

**Comment by colltoaction** [comment]
@francoSpada esto lo resolviste en otro lado?

**Comment by fdnk** [comment]
Esta resuelto, pero yo quería poder forzar más de un curso.

**Comment by francoSpada** [comment]
Ahora se pueden muchos cursos. Tendría que haberlo hecho desde el principio...

**Comment by colltoaction** [comment]
hiciste un push o todavía está en tu compu? se acostumbra a cerrar un issue desde el pull request. la clave está en poner en el mensaje "fixes #17" (por ejemplo), y automáticamente se cierra el issue y quedan linkeados.

**Comment by edittler** [comment]
Concuerdo con @tinchou. O con referenciar al issue en en mensaje del commit que resuelve la cuestión. Así se puede saber desde el issue que commits estuvieron relacionados. Eso es la trazabilidad. En fin, cosas de infoñoños (?

**Comment by fdnk** [comment]
Hay que hacer un mini-tutorial de workflow en Git. Para mi,
particularmente, lo más complicado de Git es la parte de trabajar con esas
cosas complicadas llamadas "otras personas".

2016-08-08 19:44 GMT-03:00 Ezequiel notifications@github.com:

**Comment by colltoaction** [comment]
De hecho eso es tutorial de trabajo en equipo :p. Git no tiene esas
features (pull requests, issues), sino que son propias de github y otras
páginas de trabajo colaborativo.
