### ISSUE TITLE
Agregar licencia de software libre al repositorio

### ISSUE THREAD

**Issue by AlexDaciuk** [lugfi/organizador-fiuba#19]
Tendriamos que agregar una licencia al repositorio, creo que lo que mas se adapta a la filosofia del grupo es GPL v3

**Comment by edittler** [comment]
Concuerdo con licenciar con GPL v3. De todas maneras considero que deberíamos tener la opinión final del autor original que es quien hizo la mayor parte del laburo.

**Comment by AlexDaciuk** [comment]
Alguna opinion @francoSpada ?

**Comment by colltoaction** [comment]
No había visto esto. Personalmente creo que si pedimos a todos los que usen algo de este repo (e.g. los datos) a licenciar GPL, es un poco mucho. Esos quizás podrían ir con CC.
El frontend en sí me parece que va bien con GPL porque es un producto más final. 
Más allá de eso, me parece que no nos va a cambiar en lo más mínimo porque nadie se va a poner a leer la licencia antes de hacer nada, y mergearía el PR con GPL para liquidar el tema jaja

**Comment by AlexDaciuk** [comment]
me re olvide de esto ... si, los datos (ya sea el json que armaste vos o el txt que se usaba antes) tendrían que ser CC ya que es un documento mas que software, pero si, el código del organizador tiene que ser GPL ... no se si podes poner varias licencias en un mismo repo ...

**Comment by edittler** [comment]
Cuando se abrió el issue, se consideró la licencia del código. Es común agregar al final del README.md una sección de licencia donde se podría aclarar esta dualidad de licencia según el material que se tome del repositorio.

**Comment by edittler** [comment]
Aprovechando los cambios de branches que surgieron por el issue #23, aproveché a agregar una sección de licencia en el README.md. Además de mencionar que el código fuente tiene licencia GPL (que ya está explícito en el archivo LICENSE), puse que los demás recursos tienen licencia Creative Commons CC BY-NC-SA 4.0.
