### ISSUE TITLE
Rama master se puede publicar

### ISSUE THREAD

**Issue by dato** [lugfi/organizador-fiuba#23]
Si les interesa estandarizar un toque el repo, desde hace un tiempo se puede publicar a GitHub Pages [directamente desde master](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/).

**Comment by edittler** [comment]
Excelente la información! Lo hemos discutido en Telegram y dado que en master no teníamos nada, nos pareció mejor dejar de usar el branch gh-pages. El cambio ya está aplicado en el repo.
