### ISSUE TITLE
[Sugerencia] Añadir filtro a buscador de materias

### ISSUE THREAD

**Issue by miporto** [lugfi/organizador-fiuba#9]
Cuando buscas materias y añadís el filtro por carrera el buscador te muestra materias que pertenecen a otras y solo cuando intentas agregarlas te avisa que no pertenecen a tu carrera.

**Sugerencia:** Que cuando busques materias con el filtro activado solo te muestre aquellas que sí pertenecen a tu carrera.

**Comment by colltoaction** [comment]
Buenísimo! Si te animás a implementarlo, yo te puedo dar una mano y
guiarte. No sé si sabés javascript, pero es una buena oportunidad para
aprender un poquito :D

**Comment by miporto** [comment]
Se poco, pero voy a tratar de implementarlo!

**Comment by colltoaction** [comment]
Genial!

**Comment by francoSpada** [comment]
Ya está agregada esta funcionalidad
